# Generated by Django 5.1.1 on 2025-01-14 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_review_upvotes_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='age_rating',
            field=models.CharField(choices=[('10+', 'CHILDREN'), ('16+', 'TEEN'), ('18+', 'ADULT')], default='16+', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='file_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('GERMAN', 'German'), ('SHONA', 'Shona'), ('FRENCH', 'French')], default='ENGLISH', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
